server:
  port: 8900
  servlet:
    context-path: /api
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/generator?serverTimezone=Asia/shanghai
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true # 驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/lstar/sql_generator_server/mapper/*.xml

logging:
  level:
    org:
      springframework: error

log:
  path: F:/log
  maxHistory: 30
  totalSize: 1GB
